### ISSUE TITLE
git: git & gitHub setting

### ISSUE THREAD

**Issue by crossbell8368** [1OS-DevTeam/TeamPlan#1]
## Description 

추가 or 수정이 필요한 git & GitHub 관련 파일들을 있을경우 comment를 남겨주세요

없을 경우에도 코멘트로 확인메세지 남겨주시기 바랍니다 :)

## Task

- [x] Crossbell
- [x] sani
- [x] wangkobong

**Comment by wangkobong** [comment]
> * [x]  wangkobong

**Comment by crossbell8368** [comment]
Firebase 접근파일 GoogleService-Info.plist

해당 파일만 있으면 다른 프로젝트에서 firebase 접근이 가능하기에 .gitignore 에 추가할 예정

개발 팀원분들에게는 다운로드 url 제공예정
