### ISSUE TITLE
[git] xcode 프로젝트 공유방식

### ISSUE THREAD

**Issue by crossbell8368** [1OS-DevTeam/TeamPlan#4]
## Description ( todo 설명 )

* .gitignore 설정으로 인해 xcodeproj 파일이 github로 공유되지 않음
* merge conflict의 주범이기에 제외시켰으나, git clone 시 xcode에서 열수없다는 문제발생
* xcworkspace 파일또한 .xcodeproj 을 필요로 하여 해결방안이 되지 못하였음
* .xcodeproj 없이 프로젝트를 공유하는 방안 파악 및 공유

**Comment by crossbell8368** [comment]
## 로컬에서 프로젝트 생성방식

* **ChatGPT 에 해당문제 문의시 답변받은 내용**
![스크린샷 2023-02-15 오후 1 16 49](https://user-images.githubusercontent.com/50852143/218970811-0f162d16-b4d6-4d62-af4a-a218c938dfba.png)

## 진행방법

1. **local에서 아래와 같은 설정의 xcode 프로젝트 생성**
<img width="729" alt="스크린샷 2023-02-15 오후 4 56 12" src="https://user-images.githubusercontent.com/50852143/218971280-6de8271c-85c7-4974-9462-1a8d995dd124.png">

2. **iOS 버젼을 15.0 으로 설정**

3. **fork한 repo를 clone하여 다운로드**

4. **여기까지 진행되었다면 프로젝트 파일 & git Repo 파일 2가지가 생성되어 있을 것**
![스크린샷 2023-02-15 오후 5 20 08](https://user-images.githubusercontent.com/50852143/218971905-c0ca9192-b7f7-451b-8c60-0f5568961f28.png)

5. **(!중요!) fork repo 파일에서 branch를 develop으로 우선 변경**
* 만약 default 브랜치인 main으로 두고, github 파일들을 로컬 프로젝트 폴더에 copy&paste를 진행하는 경우
  * main 브랜치에 변경사항이 발생한것으로 간주하여 develop branch로 변경이 안되는 이슈발생
  * 이 경우 로컬 프로젝트 파일에서 github 관련파일을 지우고 다시 진행하는 것을 권고

6. **develop으로 변경된 repo folder(TeamPlan_fork)의 모든 내용을 로컬 프로젝트 폴더에 copy & paste**
![스크린샷 2023-02-15 오후 5 32 41](https://user-images.githubusercontent.com/50852143/218974481-4cc89559-6835-4077-9c81-62d5116529d3.png)

7. **붙여넣기에서 '대치' 선택 시, repo의 .swift파일만 프로젝트에 덫씌워지며, 프로젝트 빌드 및 동작에 이상없음 확인**

**(Opt) 해당 mac에 github keychain이 포함되어 있는경우, 별도의 xcode 설정없이도, source control 사용가능 확인**
![스크린샷 2023-02-15 오후 5 35 01](https://user-images.githubusercontent.com/50852143/218975355-ead56b46-5254-44f6-af9d-a3204ec2f80d.png)

**Comment by wangkobong** [comment]
ContentView에서 프리뷰가 안보이는 오류가 있네요 
제가 다른 SwiftUI View 만들어서 테스트해보니 프리뷰 나오긴해서 작업 시작해보겠습니다!

**Comment by wangkobong** [comment]
프리뷰가 안되네요
<img width="507" alt="스크린샷 2023-02-15 오후 11 07 58" src="https://user-images.githubusercontent.com/61865579/219059036-61906110-6f12-4bcc-9dbe-a2ce690eed95.png">

**Comment by wangkobong** [comment]
해결했습니다!!

**Comment by crossbell8368** [comment]
확인 감사합니다 성연님 :)

**Comment by crossbell8368** [comment]
## 20230227 : 이슈상황

* xcodeproj 파일 생성시, 다른 개발자의 코드를 가져와서 생성 & 빌드하는 경우, 빌드가 제대로 진행되지 않음
* 다른 개발자가 구성한 파일구조, 에셋추가 등 작업내용이 새로 생성된 프로젝트에서 인지하지 못하여 발생하는 문제로 추측
* 이슈상황 해결을 위해 Tuist, XcodeGen 등의 도입을 논의

**Comment by crossbell8368** [comment]
## 20230306 : 이슈상황 해결

**CFBundleVersion 이슈**
--------------------------
* **상황**
: 기존 info.plist 파일로 프로젝트 빌드 및 preview 시 'CFBundleVersion does not exist' 이슈발생

* **해결**
: CFBundle 관련 default 설정값들을 info.plist 추가 후 빌드 시 해결

<details>
<summary>info.plist 설정값</summary>
<div markdown="1">

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>CFBundleDevelopmentRegion</key>
	<string>$(DEVELOPMENT_LANGUAGE)</string>
	<key>CFBundleExecutable</key>
	<string>$(EXECUTABLE_NAME)</string>
	<key>CFBundleIdentifier</key>
	<string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
	<key>CFBundleInfoDictionaryVersion</key>
	<string>6.0</string>
	<key>CFBundleName</key>
	<string>$(PRODUCT_NAME)</string>
	<key>CFBundlePackageType</key>
	<string>APPL</string>
	<key>CFBundleShortVersionString</key>
	<string>15.0</string>
	<key>CFBundleVersion</key>
	<string>15.0</string>
	<key>UIAppFonts</key>
	<array>
		<string>ArchivoBlack-Regular.ttf</string>
	</array>
	<key>UIApplicationSceneManifest</key>
	<dict>
		<key>UISceneConfigurations</key>
		<dict>
			<key>Default Configuration</key>
			<dict>
				<key>UISceneClassName</key>
				<string>UIWindowScene</string>
				<key>UISceneDelegateClassName</key>
				<string>$(PRODUCT_MODULE_NAME).SceneDelegate</string>
				<key>UISceneSessionRole</key>
				<string>window</string>
				<key>UISceneStoryboardFile</key>
				<string>Main</string>
			</dict>
		</dict>
		<key>UISupportedInterfaceOrientations</key>
		<array>
			<string>UIInterfaceOrientationPortrait</string>
			<string>UIInterfaceOrientationLandscapeLeft</string>
			<string>UIInterfaceOrientationLandscapeRight</string>
		</array>
		<key>UISupportedInterfaceOrientations~ipad</key>
		<array>
			<string>UIInterfaceOrientationPortrait</string>
			<string>UIInterfaceOrientationPortraitUpsideDown</string>
			<string>UIInterfaceOrientationLandscapeLeft</string>
			<string>UIInterfaceOrientationLandscapeRight</string>
		</array>
	</dict>
	<key>UILaunchStoryboardName</key>
	<string>LaunchScreen.storyboard</string>
</dict>
</plist>
```

</div>
</details>

**빌드 시 화면잘림 이슈**
--------------------------

* **상황**
: CFBundle 관련설정 추가 후, preview는 모두 정상출력 확인
: 빌드 시, 화면 위 & 아래 일부분이 검은 화면으로 잘리면서 크기 및 에셋배치가 무너지는 상황발생

* **해결**
: [유사이슈 확인](https://ios-development.tistory.com/275)
: project.swift 의 Resource 영역에 Launch 파일이 포함되도록 설정
: info.plist 의 'UILaunchStoryboardName' 부분에 LaunchScreen.storyboard 추가
: tuist generate 이후 Xcode project 설정 -> target 설정 -> App Icons and Launch Screen 파트 -> Launch Screen File 영역에 LaunchScreen.storyboard 설정되어 있는지 확인
:  Launch Screen File 설정 후, 빌드후 정상출력 확인

* **정상빌드 화면**
![스크린샷 2023-03-07 오후 4 35 35](https://user-images.githubusercontent.com/50852143/223355208-64babc26-5d47-491a-b14a-14451905b494.png)
